2025/01/21 10:38:03 [2025-01-21T10:38:03+07:00] ERROR: Error 1045 (28000): Access denied for user 'admisi_user1'@'_gateway' (using password: YES) | Context: Cannot Ping database | File: C:/Go Projects/uibbe_framework/cmd/main.go:19
2025/01/21 10:43:36 [2025-01-21T10:43:36+07:00] ERROR: Error 1045 (28000): Access denied for user 'admisi_user1'@'_gateway' (using password: YES) | Context: Cannot Ping database | File: C:/Go Projects/uibbe_framework/cmd/main.go:19
2025/01/21 15:34:31 [2025-01-21T15:34:31+07:00] ERROR: Error 1054 (42S22): Unknown column 'akuse_username' in 'where clause' | Context: Data Scan Error | File: C:/Go Projects/uibbe_framework/internal/service/userService.go:34
2025/01/21 16:14:56 [2025-01-21T16:14:56+07:00] ERROR: key is of invalid type | Context: Failed To Generate Token | File: C:/Go Projects/uibbe_framework/internal/controller/authController.go:32
2025/01/22 10:55:36 [2025-01-22T10:55:36+07:00] ERROR: Key: 'UserInput.Email' Error:Field validation for 'Email' failed on the 'email' tag
Key: 'UserInput.IsAktif' Error:Field validation for 'IsAktif' failed on the 'required' tag | Context: Validation failed | File: C:/Go Projects/uibbe_framework/internal/middleware/inputValidator.go:30
2025/08/14 20:41:10 [2025-08-14T20:41:10+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/14 20:41:10 [2025-08-14T20:41:10+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:273
2025/08/14 20:54:12 [2025-08-14T20:54:12+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/14 20:56:44 [2025-08-14T20:56:44+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/14 20:56:44 [2025-08-14T20:56:44+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:273
2025/08/14 21:21:54 [2025-08-14T21:21:54+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/14 21:21:54 [2025-08-14T21:21:54+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to dial LDAP server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:172
2025/08/14 22:08:59 [2025-08-14T22:08:59+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:40:55 [2025-08-15T10:40:55+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:40:55 [2025-08-15T10:40:55+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:40:55 [2025-08-15T10:40:55+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:263
2025/08/15 10:43:32 [2025-08-15T10:43:32+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:43:32 [2025-08-15T10:43:32+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:48:36 [2025-08-15T10:48:36+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:48:36 [2025-08-15T10:48:36+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:55:02 [2025-08-15T10:55:02+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:55:02 [2025-08-15T10:55:02+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:56:28 [2025-08-15T10:56:28+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 10:56:28 [2025-08-15T10:56:28+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 13:40:52 [2025-08-15T13:40:52+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 13:40:52 [2025-08-15T13:40:52+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 13:53:48 [2025-08-15T13:53:48+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 13:53:48 [2025-08-15T13:53:48+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 14:03:13 [2025-08-15T14:03:13+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 14:03:13 [2025-08-15T14:03:13+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 14:07:53 [2025-08-15T14:07:53+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 14:07:53 [2025-08-15T14:07:53+07:00] ERROR: Error 1045 (28000): Access denied for user ''@'localhost' (using password: NO) | Context: Data Scan Error | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:45
2025/08/15 14:57:48 [2025-08-15T14:57:48+07:00] ERROR: Error 1146 (42S02): Table 'akademik.users' doesn't exist | Context: Insert Registration Failed | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:118
2025/08/16 09:38:16 [2025-08-16T09:38:16+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/16 09:38:38 [2025-08-16T09:38:38+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/16 10:49:52 [2025-08-16T10:49:52+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 10:54:43 [2025-08-19T10:54:43+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 11:04:49 [2025-08-19T11:04:49+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 12:00:10 [2025-08-19T12:00:10+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 12:07:43 [2025-08-19T12:07:43+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 12:13:10 [2025-08-19T12:13:10+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 12:20:21 [2025-08-19T12:20:21+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 12:25:37 [2025-08-19T12:25:37+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 13:51:32 [2025-08-19T13:51:32+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 13:59:21 [2025-08-19T13:59:21+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 14:07:33 [2025-08-19T14:07:33+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 14:13:11 [2025-08-19T14:13:11+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 14:15:14 [2025-08-19T14:15:14+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 15:02:57 [2025-08-19T15:02:57+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 15:39:22 [2025-08-19T15:39:22+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 15:46:42 [2025-08-19T15:46:42+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 16:10:50 [2025-08-19T16:10:50+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 16:16:23 [2025-08-19T16:16:23+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 16:18:55 [2025-08-19T16:18:55+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 16:22:29 [2025-08-19T16:22:29+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/19 16:56:11 [2025-08-19T16:56:11+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/20 10:10:11 [2025-08-20T10:10:11+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/20 10:30:33 [2025-08-20T10:30:33+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/20 10:31:09 [2025-08-20T10:31:09+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/20 11:27:54 [2025-08-20T11:27:54+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/20 12:04:43 [2025-08-20T12:04:43+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:276
2025/08/20 12:07:49 [2025-08-20T12:07:49+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:276
2025/08/20 12:08:34 [2025-08-20T12:08:34+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:276
2025/08/20 12:12:31 [2025-08-20T12:12:31+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:303
2025/08/20 16:04:29 [2025-08-20T16:04:29+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:08:45 [2025-08-20T16:08:45+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:12:26 [2025-08-20T16:12:26+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:16:34 [2025-08-20T16:16:34+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:18:51 [2025-08-20T16:18:51+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:21:08 [2025-08-20T16:21:08+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:46:09 [2025-08-20T16:46:09+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:53:53 [2025-08-20T16:53:53+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:305
2025/08/20 16:57:20 [2025-08-20T16:57:20+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/20 17:01:05 [2025-08-20T17:01:05+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/20 17:01:39 [2025-08-20T17:01:39+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/20 21:03:14 [2025-08-20T21:03:14+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/20 21:21:29 [2025-08-20T21:21:29+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/20 21:23:28 [2025-08-20T21:23:28+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/20 21:54:37 [2025-08-20T21:54:37+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/20 21:58:47 [2025-08-20T21:58:47+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 09:25:36 [2025-08-21T09:25:36+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 09:34:24 [2025-08-21T09:34:24+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 09:41:40 [2025-08-21T09:41:40+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 09:48:38 [2025-08-21T09:48:38+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 09:52:34 [2025-08-21T09:52:34+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 10:14:38 [2025-08-21T10:14:38+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 10:55:04 [2025-08-21T10:55:04+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 10:58:43 [2025-08-21T10:58:43+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 13:53:20 [2025-08-21T13:53:20+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 13:56:01 [2025-08-21T13:56:01+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 14:58:54 [2025-08-21T14:58:54+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 15:05:54 [2025-08-21T15:05:54+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 15:06:50 [2025-08-21T15:06:50+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 15:11:45 [2025-08-21T15:11:45+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 15:14:08 [2025-08-21T15:14:08+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 15:18:35 [2025-08-21T15:18:35+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 15:26:18 [2025-08-21T15:26:18+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 15:29:58 [2025-08-21T15:29:58+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/21 16:11:04 [2025-08-21T16:11:04+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 09:28:16 [2025-08-22T09:28:16+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 09:52:05 [2025-08-22T09:52:05+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:20:48 [2025-08-22T10:20:48+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:21:09 [2025-08-22T10:21:09+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:21:46 [2025-08-22T10:21:46+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:28:25 [2025-08-22T10:28:25+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:29:06 [2025-08-22T10:29:06+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:36:55 [2025-08-22T10:36:55+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:51:18 [2025-08-22T10:51:18+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:55:06 [2025-08-22T10:55:06+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:55:59 [2025-08-22T10:55:59+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 10:57:48 [2025-08-22T10:57:48+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 14:00:15 [2025-08-22T14:00:15+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 14:10:38 [2025-08-22T14:10:38+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/22 14:16:05 [2025-08-22T14:16:05+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/23 11:54:57 [2025-08-23T11:54:57+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:06:39 [2025-08-25T13:06:39+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:12:26 [2025-08-25T13:12:26+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:16:03 [2025-08-25T13:16:03+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:18:21 [2025-08-25T13:18:21+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:19:47 [2025-08-25T13:19:47+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:21:21 [2025-08-25T13:21:21+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:24:45 [2025-08-25T13:24:45+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:27:47 [2025-08-25T13:27:47+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:29:34 [2025-08-25T13:29:34+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:31:52 [2025-08-25T13:31:52+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:31:52 [2025-08-25T13:31:52+07:00] ERROR: record not found | Context: Data Not Found | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:54
2025/08/25 13:31:57 [2025-08-25T13:31:57+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:34:22 [2025-08-25T13:34:22+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:40:29 [2025-08-25T13:40:29+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:43:08 [2025-08-25T13:43:08+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:46:35 [2025-08-25T13:46:35+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 13:51:38 [2025-08-25T13:51:38+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:06:41 [2025-08-25T14:06:41+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:16:30 [2025-08-25T14:16:30+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:19:17 [2025-08-25T14:19:17+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:20:38 [2025-08-25T14:20:38+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:22:36 [2025-08-25T14:22:36+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:24:49 [2025-08-25T14:24:49+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:25:54 [2025-08-25T14:25:54+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:26:47 [2025-08-25T14:26:47+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:27:33 [2025-08-25T14:27:33+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:28:37 [2025-08-25T14:28:37+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:31:00 [2025-08-25T14:31:00+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:31:41 [2025-08-25T14:31:41+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:33:24 [2025-08-25T14:33:24+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:37:29 [2025-08-25T14:37:29+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:39:28 [2025-08-25T14:39:28+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:40:41 [2025-08-25T14:40:41+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:42:32 [2025-08-25T14:42:32+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:44:59 [2025-08-25T14:44:59+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:46:35 [2025-08-25T14:46:35+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:48:11 [2025-08-25T14:48:11+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:52:01 [2025-08-25T14:52:01+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:53:08 [2025-08-25T14:53:08+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 14:53:08 [2025-08-25T14:53:08+07:00] ERROR: record not found | Context: Data Not Found | File: C:/xampp/htdocs/Testing-golang/internal/service/userService.go:54
2025/08/25 14:53:16 [2025-08-25T14:53:16+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/25 16:27:23 [2025-08-25T16:27:23+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 09:35:02 [2025-08-26T09:35:02+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 10:09:28 [2025-08-26T10:09:28+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 10:13:03 [2025-08-26T10:13:03+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 10:24:16 [2025-08-26T10:24:16+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:14:22 [2025-08-26T11:14:22+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:17:10 [2025-08-26T11:17:10+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:17:40 [2025-08-26T11:17:40+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:19:41 [2025-08-26T11:19:41+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:20:14 [2025-08-26T11:20:14+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:23:25 [2025-08-26T11:23:25+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:25:45 [2025-08-26T11:25:45+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
2025/08/26 11:28:35 [2025-08-26T11:28:35+07:00] ERROR: LDAP Result Code 200 "Network Error": dial tcp :389: connectex: No connection could be made because the target machine actively refused it. | Context: Failed to Dial to LDAP Server | File: C:/xampp/htdocs/Testing-golang/internal/controller/authController.go:304
